### ISSUE TITLE
Change feature name

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/Sample-Commander#30]
The feature name is currently set to "featureName".
It should be set to something like "Sample Commander"

**Comment by AObuchow** [comment]
@ingomohr I saw there's a feature.properties, which defines the featureName, but for some reason it's not being used?

To reproduce, build the project with mvn verify, then install the plugin locally. The feature name will say "featureName"

**Comment by ingomohr** [comment]
> @ingomohr I saw there's a feature.properties, which defines the featureName, but for some reason it's not being used?
> 
> To reproduce, build the project with mvn verify, then install the plugin locally. The feature name will say "featureName"

@AObuchow Hm, I'll check on that.

**Comment by ingomohr** [comment]
@AObuchow  Yep, you're right. The name is not resolved from the ``feature.properties``file.
I'll create a PR for this.

**Comment by ingomohr** [comment]
@AObuchow  Sorry ;) - I should've tested this better before.

**Comment by AObuchow** [comment]
@ingomohr no worries, thank you for the quick fix :)
