### ISSUE TITLE
View flattened directory structure in file manager

### ISSUE THREAD

**Issue by AObuchow** [AObuchow/Sample-Commander#33]
It’d be nice to be able to view a directory as “flattened”, that is to say all contents of any child directories are visible from the parent (and child directories are hidden themselves).

This could be very useful when “sort by date modified/created” will be available, since any new files added to a directory will be quick to find.

**Comment by AObuchow** [comment]
In this mode, drag support should probably be disabled as well as paste.

**Comment by AObuchow** [comment]
It will need probably two icons, one to indicate the flat mode is enabled and one to indicate the normal directory-hierarchy mode is enabled.

I was thinking maybe [this](https://github.com/tailwindlabs/heroicons/blob/master/solid/view-list.svg) for flat mode and [this](https://github.com/tailwindlabs/heroicons/blob/master/solid/folder.svg) for directory-hierarchy mode.

Although now that I think of it, maybe a [closed folder](https://github.com/tailwindlabs/heroicons/blob/master/solid/folder.svg) could represent directory-hierarchy mode, and an [opened folder](https://github.com/tailwindlabs/heroicons/blob/master/solid/folder-open.svg) could represent flat mode?

@ingomohr any thoughts or suggestions? :P

**Comment by ingomohr** [comment]
> It will need probably two icons, one to indicate the flat mode is enabled and one to indicate the normal directory-hierarchy mode is enabled.
> 
> I was thinking maybe [this](https://github.com/tailwindlabs/heroicons/blob/master/solid/view-list.svg) for flat mode and [this](https://github.com/tailwindlabs/heroicons/blob/master/solid/folder.svg) for directory-hierarchy mode.
> 
> Although now that I think of it, maybe a [closed folder](https://github.com/tailwindlabs/heroicons/blob/master/solid/folder.svg) could represent directory-hierarchy mode, and an [opened folder](https://github.com/tailwindlabs/heroicons/blob/master/solid/folder-open.svg) could represent flat mode?
> 
> @ingomohr any thoughts or suggestions? :P

Hm, I like the folder vs the hamburger better - even though the hamburger has actually different semantics. :)
Closed vs Open-Folders suggest imho that the (closed) no contents are shown or (open) the contents are shown.

But if I get it right, this is more about showing only the files in the subtree.

**Comment by AObuchow** [comment]
@ingomohr thanks for the feedback, yes this is about deciding whether to show files in the subtree or hide them under a folder. I do agree, that folder vs hamburger might be better, as they represent better what things would look like (visually).

Ie. the hamburger icon is closer to a list of files - in flat mode, you will only see files. The folder icon lets the user know that they will see folder's in the file manager.

**Comment by ingomohr** [comment]
> @ingomohr thanks for the feedback, yes this is about deciding whether to show files in the subtree or hide them under a folder. I do agree, that folder vs hamburger might be better, as they represent better what things would look like (visually).
> 
> 
> 
> Ie. the hamburger icon is closer to a list of files - in flat mode, you will only see files. The folder icon lets the user know that they will see folder's in the file manager.

Maybe you could use a list icon instead. It's like a hamburger, only with a little bullet on the left side. ^^

**Comment by AObuchow** [comment]
Fixed in https://github.com/AObuchow/Sample-Commander/commit/a4c749b2cecd6d513179b1ff38393abeaed48a44 :) The list icon could be better, it doesn't have the bullet's on the left side :P Nedd to find a better one, but that can be for another bug :)
